[tool.poetry]
name = "deeplib"
version = "0.1.1.1"
description = ""
authors = ["Michael Kalashnikov <m.kalashnikov@quantumobile.com>"]

[tool.poetry.dependencies]
python = "^3.6.5"

[tool.poetry.dev-dependencies]
black = "^21.9b0"
isort = "^5.9.3"
mypy = "^0.910"
pytest = "^6.2.5"

[tool.isort]
profile = "black"

[tool.black]
exclude = '''
/(
    \.mypy_cache\
  | etc
)/
'''

[tool.mypy]
disallow_untyped_defs = true
ignore_missing_imports = true
python_version = "3.6"
exclude = '''
/(
    \.mypy_cache\
  | etc
)/
'''


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
